# Classification of Swiss cities Satellite Imagery using Deep Neural Networks

 

This project aims to classify the following swiss cities: **Zurich, Geneva, Basel, Lausanne, Bern, Winterthur, Luzern, St_Gallen, Lugano, Biel**
To accomplish this, Images from the Swiss Federal Office of Topography will be used. These images are available open source. and cover the entirety of Switzerland.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Flatten, Dropout, BatchNormalization

2024-04-27 18:10:52.390170: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
data = pd.read_csv('data/csv/Ten_cities_lower.csv')

In [4]:
def string_to_array(string):
    elements = string.strip('[]').split(',')
    array = np.array(elements, dtype=int).reshape((100, 100))
    return array

data['Array'] = data['Array'].apply(string_to_array)


In [5]:
City_list = ['Zurich', 'Geneva', 'Basel', 'Lausanne', 'Bern', 'Winterthur', 'Luzern', 'St_Gallen', 'Lugano', 'Biel']

label_encoder = LabelEncoder()
data['Encoded_loc'] = label_encoder.fit_transform(data['Location'])

In [16]:
#split the dataset
X = np.array(data['Array'].to_list())
y = np.array(data['Encoded_loc'].to_list())
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [17]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [18]:
model = Sequential()
model.add(Flatten(input_shape=(100, 100)))
model.add(Dense(128, activation='relu'))
model.add(Dense(10))

#compile the model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

#train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=1)

Epoch 1/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.0924 - loss: 4.6846
Epoch 2/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.0904 - loss: 2.3767
Epoch 3/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1353 - loss: 2.3051
Epoch 4/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.1535 - loss: 2.2546
Epoch 5/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.1333 - loss: 2.2617
Epoch 6/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1398 - loss: 2.2562
Epoch 7/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.1406 - loss: 2.2729
Epoch 8/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.1517 - loss: 2.2233
Epoch 9/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.1515 - loss: 2.2289
Epoch 10/10
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.1524 - loss: 2.2132


In [19]:
test_loss, test_acc = model.evaluate(X_test,  y_test, verbose=2)

print('\nTest accuracy:', test_acc)

y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs)

cm = confusion_matrix(y_test, y_pred)
print(cm)

8/8 - 0s - 29ms/step - accuracy: 0.1695 - loss: 2.2540

Test accuracy: 0.16949152946472168
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[ 0  0  0  0  0  0  0  0  0 14]
 [ 0  0  0  0  0  0  0  0  0 25]
 [ 0  0  0  0  0  0  0  0  0 12]
 [ 0  0  0  0  0  0  0  0  0 11]
 [ 0  0  0  0  0  0  0  0  0 31]
 [ 0  0  0  0  1  0  0  0  0 41]
 [ 0  0  0  0  0  0  0  0  0 20]
 [ 0  0  0  0  0  0  0  0  0 17]
 [ 0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0 40]]


## Only keeping 2 cities

In [25]:
#Only keep 2 cities
two_city = data[data['Location'].isin(('Lausanne', 'Zurich'))]
two_city = pd.DataFrame(two_city)
two_city['Encoded_loc'] = label_encoder.fit_transform(two_city['Location'])

In [26]:
#split the dataset
X_2 = np.array(two_city['Array'].to_list())
y_2 = np.array(two_city['Encoded_loc'].to_list())
X_train2, X_test2, y_train2, y_test2 = train_test_split(X_2, y_2, test_size=0.3)

In [27]:
X_train2 = X_train2 / 255.0
X_test2 = X_test2 / 255.0

In [28]:
model2 = Sequential()
model2.add(Flatten(input_shape=(100, 100)))
model2.add(Dense(128, activation='relu'))
model2.add(Dense(10))

#compile the model
model2.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

#train the model
model2.fit(X_train2, y_train2, epochs=10)

Epoch 1/10


/Users/edwinvincendeau/Desktop/2eme semestre/Advanced/ADA/Swisscities/.venv/lib/python3.10/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.3608 - loss: 2.5626
Epoch 2/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.5185 - loss: 2.5141
Epoch 3/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.5491 - loss: 1.7093
Epoch 4/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.4374 - loss: 1.8609
Epoch 5/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.4456 - loss: 1.3038
Epoch 6/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.5470 - loss: 1.8882
Epoch 7/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5037 - loss: 2.1885
Epoch 8/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.5212 - loss: 2.1133
Epoch 9/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.4320 - loss: 2.1464
Epoch 10/10
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.5854 - loss: 0.7991


In [29]:
test_loss2, test_acc2 = model2.evaluate(X_test2,  y_test2, verbose=2)
print('\nTest accuracy:', test_acc2)

y_pred_probs = model2.predict(X_test2)
y_pred = np.argmax(y_pred_probs, axis=1)

cm = confusion_matrix(y_test2, y_pred)
print(cm)

3/3 - 0s - 123ms/step - accuracy: 0.5652 - loss: 1.5335

Test accuracy: 0.5652173757553101
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[ 0 30]
 [ 0 39]]
